/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "donkey_constants.h"

namespace donkey { namespace api {

const donkeyConstants g_donkey_constants;

donkeyConstants::donkeyConstants() {
}

}} // namespace

