/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef donkey_CONSTANTS_H
#define donkey_CONSTANTS_H

#include "donkey_types.h"

namespace donkey { namespace api {

class donkeyConstants {
 public:
  donkeyConstants();

};

extern const donkeyConstants g_donkey_constants;

}} // namespace

#endif
