// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Donkey.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::donkey::api;

class DonkeyHandler : virtual public DonkeyIf {
 public:
  DonkeyHandler() {
    // Your initialization goes here
  }

  void ping(PingResponse& _return, const PingRequest& request) {
    // Your implementation goes here
    printf("ping\n");
  }

  void search(SearchResponse& _return, const SearchRequest& request) {
    // Your implementation goes here
    printf("search\n");
  }

  void insert(InsertResponse& _return, const InsertRequest& request) {
    // Your implementation goes here
    printf("insert\n");
  }

  void misc(MiscResponse& _return, const MiscRequest& request) {
    // Your implementation goes here
    printf("misc\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DonkeyHandler> handler(new DonkeyHandler());
  shared_ptr<TProcessor> processor(new DonkeyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

